model:
  hidden_size: 
   name: hidden_size
   low: 6
   high: 24 
optim:
  optim_name: 
    name: optimizer
    choices: 
      - Adam
      - SGD # - で始まる要素はリスト
  lr:
    name: lr
    low: 1e-5
    high: 1e-1